name: GitHub Actions Demo
on:
  push:
    branches: [ 'dev' ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update RDS Schema
        run: APP_ENV=test script/update_rds_schema.sh

      - name: Deploy Backend Server
        run: APP_ENV=test script/deploy.sh